name: UnitTest

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: phpunit
      run: |
        php -v
        cd php-test-example
        docker-compose up -d
        composer install
        docker-compose exec -T php bash -c "vendor/bin/phpunit"